# -*- coding: utf-8 -*-
"""Práctica 6 (Listas parte II).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEJLduumWG7j-C39gyJluFUeil3cn1nS

# **Práctica 6: Listas parte 2** 
**Alumno:** Christian Geovany Muñoz Rodríguez \\
**Código:** 221350605

# **Ejercicio 1**
"""

'''Defina 5 listas distintas (L1, L2, L3, L4, L5), una lista numérica, una lista de letras, una lista de cadenas y
dos listas combinadas y realice lo siguiente:'''

my_list1 = [1,2,3,4,5,6,7,8,9,1.2,2.3,3.4,4.5,5.6,6.7,7.8,8.9]
my_list2 = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','u','U']
my_list3 = ['Shrek','Bee Movie','Los simpson','Kung Fu Panda','Killer Bean']
my_list4 = [12,456,234,'Hola','Mundo','El pepe','a','b','d']
my_list5 = ['Coca COla','Pepsi','Sprite','c','p','s','22.45','67','123','567']

#Imprima el número de elementos que contiene cada lista por medio de la función len().
print(f"Elementos de la lista 1: {len(my_list1)}\nElementos de la lista 2: {len(my_list2)}\nElementos de la lista 3: {len(my_list3)}\nElementos de la lista 4: {len(my_list4)}\nElementos de la lista 5: {len(my_list5)}")

#Defina una nueva lista (L6) a partir de la concatenación de L4 + L1 + L3 e imprímala.
my_list6 = my_list4 + my_list1 + my_list3
print(f"Lista concatenada: {my_list6}")

#Defina una nueva lista (L7) a partir de repetir L2 cuatro veces e imprímala.
my_list7 = my_list2*4
print(f'Lista repetida: {my_list7}')

#Imprima el valor máximo y el mínimo de L5
print(f"El valor máximo de la lista 5 es: {max(my_list5)}\nEl valor mínimo de la lista 5 es: {min(my_list5)}")

#Busque si dentro de la lista numérica se encuentra el número 10 e imprima el resultado.
if 10 in my_list1:
  r = 'Sí'
else:
  r = 'no'

print(f"10 {r} está en la lista 1")

#Busque si dentro de la lista de letras se encuentra la letra U e imprima el resultado.
if ('u' in my_list2) or ('U' in my_list2) :
  r = 'Sí'
else:
  r = 'No'

print(f"U {r} está en la lista 2")

#Cuente cuantas veces se repite el valor de algún elemento de la lista L7 e imprima el resultado.
print(f"'u' se repite {my_list7.count('u')} veces en la lista 7")

"""# **Ejercicio 2**"""

'''
Realizar un programa que sume todos los elementos de una lista y despliegue el resultado.
'''
numeros = [123,45,765,897,5.8,89,678,1.3456]#definición de la lista

suma = 0 

print(f"Lista de números: {numeros}")

#suma de los elementos
for numero in numeros:
  suma += numero
  
print(f"Suma de los números: {suma}")

"""# **Ejercicio 3**"""

'''
Solicite al usuario el número de elementos a guardar y llene una lista con los elementos otorgados por el
usuario. Una vez llenados los datos despliegue la lista original, la lista ordenada, la lista original y la lista
ordenada en reversa, el máximo y el mínimo.
'''
#Solicite el número de elementos que contendrá la lista
numero_elementos = int(input("Dame el número de elementos a guardar: "))
lista=[]

#El usuario ingresa los datos
for i in range(1,numero_elementos+1): 
  elemento = int(input(f"Ingrese el elemento {i} (valor entero) de la lista: "))
  lista.append(elemento)



#Lista original
print(f'Lista original: {lista}')

#Lista original en reversa
lista.reverse()
print(f'Lista en reversa: {lista}')

#Lista ordenada
lista.sort()
print(f'Lista ordenada: {lista}')

#Lista ordenada en reversa
lista.reverse()
print(f'Lista ordenada en reversa: {lista}')

#Elemento máximo y elemento mínimo
print(f'Elemento máximo: {max(lista)}')
print(f'Elemento mínimo: {min(lista)}')

"""# **Ejercicio 4**"""

'''
Defina una lista de calificaciones y encuentre la primera, la segunda y la tercera calificación más alta así
como las dos calificaciones más bajas. Nota: La lista debe contener elementos repetidos.
'''

#Lista de calificaciones
lista = [34,45,89,98,76,56,45,100,98,72,72,98,65,83,92,65,48,91,72,64,92,65,78,49,57,63,81,75]
nueva_lista= []

print(f"Lista de calificaciones: {lista}")

#Eliminación de elementos repetidos
for elemento in lista:
  if elemento not in nueva_lista:
    nueva_lista.append(elemento)

#Ordenamiento de la lista
nueva_lista.sort()
nueva_lista.reverse()

#Output de resultados
print(f"Primer lugar: {nueva_lista[0]}\nSegundo lugar: {nueva_lista[1]}\nTercer lugar: {nueva_lista[2]}\nPenúltimo lugar: {nueva_lista[-2]}\nÚltimo lugar: {nueva_lista[-1]}\n")

"""# **Ejercicio 5**"""

'''Definir una lista de números y guardar en una nueva lista a todos los elementos que sean menores a 10.
A su vez borrar a todos los elementos repetidos y guardarlos en otra lista. Desplegar todas las listas.
Ejemplo:'''
#Definición de la lista
numeros = [24, 18, 24, 22, 18, 16, 2, 25, 19, 3, 12, 5, 18, 23, 25, 11, 15, 15, 22, 9, 9, 23, 2, 25, 4, 2, 9, 7, 19, 6]
menores = [] #Lista de números menores
sin_repetir = []#Lista de números sin elmentos repetidos

print(f'Lista de números: {numeros}')
#Filtración de números menores a 10
for numero in numeros:
  if numero < 10:
    menores.append(numero)

#Filtración de números repetidos
for numero in numeros:
  if numero not in sin_repetir:
    sin_repetir.append(numero)

#Output de resultados
menores.sort()
print(f'Numeros menores a 10: {menores}')
print(f'Nueva lista sin elementos repetidos: {sin_repetir}')