# -*- coding: utf-8 -*-
"""Práctica 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuD1YByPltU4hzxDilGGaDopmLSzgQro

## **Práctica 2: Sentencias selectivas**

**Alumno:** Christian Geovany Muñoz Rodríguez 

 **Código:** 221350605

# **Ejercicio 1**
"""

# Solicite al usuario que ingrese 5 números
print("Ingrese 5 números diferentes")
a = float (input("\nDame un número: "))
b = float (input("\nDame un segundo número: "))
c = float (input("\nDame un tercer número: "))
d = float (input("\nDame un cuarto número: "))
e = float (input("\nDame un quinto número: "))

# Imprimir el mayor de ellos

if (a > b) and (a> c) and (a > d) and (a > e):
  print("\nEl numero mayor es", a)
elif (b > a) and (b > c) and (b > d) and (b > e):
  print("\nEl numero mayor es", b)
elif (c > a) and (c > b) and (c > d) and (c > e):
  print("\nEl numero mayor es", c)
elif (d > a) and (d > b) and (d > c) and (d > e):
  print("\nEl numero mayor es", d)
elif (e > a) and (e > b) and (e > c) and (e > d):
  print("\nEl numero mayor es", e)
else:
  print("\nTodos los números son iguales")

#Imprimir el menor de ellos

if (a < b) and (a < c) and (a < d) and (a < e):
  print("\nEl numero menor es", a)
elif (b < a) and (b < c) and (b < d) and (b < e):
  print("\nEl numero menor es", b)
elif (c < a) and (c < b) and (c < d) and (c < e):
  print("\nEl numero menor es", c)
elif (d < a) and (d < b) and (d < c) and (d < e):
  print("\nEl numero menor es", d)
elif (e < a) and (e < b) and (e < c) and (e < d):
  print("\nEl numero menor es", e)

"""# **Ejercicio 2**"""

# Solicite un año

año = int (input("Ingrese un año: "))

# Imprima si ese año es bisiesto o no

if (año % 4 == 0) and (año % 100 != 0):
  print("Su año es bisiesto")
else:
  print("Su año no es bisiesto")

"""# **Ejercicio 3**"""

#Solicite al usuario la cantidad de segundos 

segundos = int (input("ingrese su tiempo en el estacionamiento en segundos: "))

# Calculo de las variables

horas = (segundos // 3600) * 15
sub_horas = (segundos // 3600) - 4
total_horas = ((segundos // 3600) * 15) + (sub_horas * 10)
descuento = total_horas * 0.80

#Imprimir el monto total a pagar

if segundos <= 659:
  print("Su estacionamiento es gratis")
elif 659 < segundos <= 1800:
  print("Usted paga 6 pesos")
elif 1800 < segundos <= 14399:
  if 1800 < segundos <=3600:
    print("Usted paga 15 pesos")
  else: 
    print("Usted paga", horas,"pesos")
elif 14399 < segundos <= 36000:
  if segundos <= 17999: 
     print("Usted paga 60 pesos")
  else:
    print("Usted paga", total_horas,"pesos")
elif  segundos > 36000:
  print("Usted paga", descuento,"pesos")

"""# **Ejercicio 4**"""

# Proporciona un menú al usuario

print("------Bienvenido al conversor de unidades de temperatura------")
print("""

De celsius (°C) a Farenheit (°F)  [Presione 1] 

De celsius (°C) a Kelvin (°K)  [Presione 2]

De Farenheith (°F) a Celsius (°C)  [Presione 3]

De Kelvin (°K) a Celsius (°C)  [Presione 4]  """) 
opc = int (input("\nPresione una tecla para elegir una opción: "))

# Solicite la temperatura e imprima la respectiva conversión

if opc == 1:
  c = float (input("\nIngrese los grados Celsius que desee convertir: "))
  f = (c * (9 / 5)) + 32
  print(c,"°C equivalen a",f,"°F")
elif opc == 2:
  c = float (input("\nIngrese los grados Celsius que desee convertir: "))
  k = c + 273.15
  print(c,"°C equivalen a",k,"°K")
elif opc == 3:
  f = float (input("\nIngrese los grados Farenheith que desee convertir: "))
  c = (f-32) * (5/9)
  print(f,"°F equivalen a",c,"°C")
elif opc == 4:
  k = float (input("\nIngrese los grados Kelvin que desee convertir: "))
  c = k - 273.15
  print(k,"°K equivalen a",c,"°C")
else:
  print("\nIngrese una opción valida")

"""# **Ejercicio 5**"""

import getpass

print("¡ESTE ES EL JUEGO DE ROCA, PAPEL, TIJERA, LAGARTO, SPOCK!")
print("""

Turno del jugador 1...

Elija una opción: 

ROCA....[R]\n
PAPEL...[P]\n
TIJERA..[T]\n
LAGARTO.[L]\n
SPOCK...[S]
""")

j1 = getpass.getpass("Escriba su elección: ")
j1 = j1.upper()

if (j1 != "R") and (j1 != "P") and (j1 != "T") and (j1 != "L") and (j1 != "S"):
  print("\nIngrese una opción valida...")
else:
  print("""

Turno del jugador 2...

Elija una opción: 

ROCA....[R]\n
PAPEL...[P]\n
TIJERA..[T]\n
LAGARTO.[L]\n
SPOCK...[S]
""")
  
  j2 = getpass.getpass("Escriba su elección: ")
  j2 = j2.upper()
  
  if (j2 != "R") and (j2 != "P") and (j2 != "T") and (j2 != "L") and (j2 != "S"):
    print("\nIngrese una opción valida...")
  else:
    print("\n***** Resultado de la partida *****")
    if j1 == j2:
      print("\nEl jugador 1 eligió: {}\nEl jugador 2: {}\nEmpate... ".format(j1, j2))
    elif (j1 == "R" and j2 == "T") or (j1 == "P" and j2 == "R") or (j1 == "T" and j2 == "P") or (j1 == "R" and j2 == "L") or (j1 == "L" and j2 == "S") or (j1 == "S" and j2 == "T") or (j1 == "T" and j2 == "L") or (j1 == "L" and j2 == "P") or (j1 == "P" and j2 == "S") or (j1 == "S" and j2 == "R"):
      print("\nEl jugador 1 eligió: {}\nEl jugador 2 eligió: {}\nGanó el jugador 1...".format(j1, j2))
    else:
      print("\nEl jugador 1 eligió: {}\nEl jugador 2 eligió: {}\nGanó el jugador 2...".format(j1, j2))

print("\n**********")
print("\nFin de la partida.")