# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16o0iJnDzJ8slRmnP-rCP_OrHeCvU0l6l

# ***Variables y tipos de dato***
"""

# Celda de código
# Declaración de variables y su respectiva expresión

E1 = 9+3*16/2**3-5/2
E2 = 6 + 2 * (7 - (4 + 2)) - 3 * (10 + 3**2 / 6)
E3 = 9 % 5 + (not (5 * 4 % 3 * 7 < 33 or 27 / 2 * 3 <= 10 * 3 / 10))
E4 = 15 / 3 + 4 * 3**2 - 5 * 6
E5 = (6 * 3 + 8 - 9 / 3 + 2**4) / 2
E6 = 2 + 4**2 * (6 * (1 - (7 + 2)/9)) + 5
E7 = 8 * ((not (7 / 4 > 2) or 9 > 9) and (3 >= 7 / 3 or 1 + 4 >= 9 / 2)) + 5

# Imprimir el resultado para cada variable

print("Resultado del ejemplo 1:", E1)
print("Resultado del ejemplo 2:", E2)
print("Resultado del ejemplo 3:", E3)
print("Resultado del ejemplo 4:", E4)
print("Resultado del ejemplo 5:", E5)
print("Resultado del ejemplo 6:", E6)
print("Resultado del ejemplo 7:", E7)